[package]
name = "rscrape"
version = "0.1.0"
edition = "2021"
authors = ["Joakim Wilhelmsson"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
colored = "2.0.0"
reqwest = { version = "0.11.17", features = ["blocking", "json"] }
scraper = "0.16.0"
