[package]
name = "http-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
html5ever = "0.26.0"
html_parser = "0.6.3"
reqwest = { version = "0.11.17", features = ["blocking", "json"] }
serde = "1.0.162"
serde_json = "1.0.96"
